[package]
name = "qrs"
version = "0.1.0"
authors = ["hmb <humberto.munozb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["qrs-core", "qrs-timed"]

[dependencies]
alga = "0.9"
approx = {version = "0.3", features=["num-complex"]}
lapack-traits = {version = "0.2.2", features=["simba"]}
cauchy = "0.2.2"
cblas = "0.2.0"
condest = {git = "https://github.com/hmunozb/rust-condest.git", branch="qrs-dep"}
lapacke = "0.2.0"
expm = {git = "https://github.com/hmunozb/rust-expm.git", branch="qrs-dep"}
integrators = {git = "https://github.com/hmunozb/integrators.git", default-features=false, features=["gsl","no_gslcblas"]}
#integrators = {version="0.0.3", default-features=false, features=["gsl"]}
interpolation = "0.2.0"
itertools = "0.8.0"
itertools-num = "0.1.3"
num-complex = {version="0.2", features=["serde"]}
num-traits = "0.2.8"
ndarray = {version="0.13", features=["rayon"]}
ndarray-linalg = "0.12"
complex-polygamma = {git="ssh://git@github.com/hmunozb/complex-polygamma.git", rev="e7388bd"}
log = "0.4.8"
nalgebra = {version="0.21", features=["serde-serialize"]}
qrs-core = {path="qrs-core"}
qrs-timed = {path="qrs-timed"}
rand = "0.7.2"
rand_distr = "0.2.2"
rand_xoshiro = "0.4.0"
rayon = "1.0"
serde = {version = "1.0", features = ["derive"] }
simd-phys = {git="https://github.com/hmunozb/simd-phys-rs.git"}
spin-langevin = {git="https://github.com/hmunozb/spin-langevin.git"}
smallvec = "1.0.0"
ndarray-stats = "0.3"
vec_ode = {git="https://github.com/hmunozb/vec-ode.git", branch="qrs-dep"}

[dev-dependencies]
criterion = "0.3"
#cblas-sys = "0.1.4"
#openblas-src = "0.7.0"
openblas-src = {version="0.9", default-features=false, features=["system"]}
lapacke-sys = "0.1.4"
simple_logger = "1.3.0"

[[bench]]
name = "qrs_bench"
harness = false
path = "benches/lib.rs"